window.JOGO_QUESTS = [
  {
    "id": "a32eeefb-f8e9-4d55-9523-31e6d3bf5eb2",
    "title": "trianon",
    "location": "Sporting, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "فين المكان اللي أجيال إسكندرانية اتجمعت فيه عشان يشربوا قهوة وياكلوا حلويات تحت حوائط تاريخية عتيقة؟",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.9,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "trianon",
    "title_ar": "تريانون",
    "clue_en": "Where generations of Alexandrians have gathered for coffee and pastries beneath timeless historic walls.",
    "clue_ar": "فين المكان اللي أجيال إسكندرانية اتجمعت فيه عشان يشربوا قهوة وياكلوا حلويات تحت حوائط تاريخية عتيقة؟",
    "riddle_answer": "trianon",
    "riddle_answer_ar": "تريانون",
    "riddle_accepted_answers": [
      "trianon",
      "تريانون"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Look for the classic period decor and art on the walls.",
      "It is located right in the city center near Ramleh station."
    ],
    "tips_ar": [
      "دور على الديكور الكلاسيكي والفن الموجود على الحوائط.",
      "المكان موجود في وسط البلد قرب محطة الرمل."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: historic wall paintings",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: اللوحات الجدارية التاريخية",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "historic wall paintings",
    "target_object_prompt_ar": "اللوحات الجدارية التاريخية",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "Trianon is one of Alexandria's most iconic historic cafes and pastry shops, offering an elegant period setting filled with classic charm and wonderful wall paintings.",
    "description_ar": "تريانون هو واحد من أعرق وأشهر المقاهي ومحلات الحلويات في الإسكندرية، بيقدم أجواء كلاسيكية ساحرة ولوحات جدارية تاريخية تنطق بعبق الماضي.",
    "category": "history",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "ca828e43-7967-47a8-8e4b-69ff3737b411",
    "title": "PuffyPops",
    "location": "35 Abd El-Moneim Riad, Abu An Nawatir, Alexandria 00203 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "فين المكان اللي البان كيك والحلويات اللذيذة فيه بتعدل المزاج وتطيرك للسابع سما؟",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "PuffyPops",
    "title_ar": "بوفي بوبس",
    "clue_en": "Where sweet puffy treats, pancakes, and warm vibes cure any meltdown into seventh-sky happiness.",
    "clue_ar": "فين المكان اللي البان كيك والحلويات اللذيذة فيه بتعدل المزاج وتطيرك للسابع سما؟",
    "riddle_answer": "PuffyPops",
    "riddle_answer_ar": "بوفي بوبس",
    "riddle_accepted_answers": [
      "puffypops",
      "بوفي بوبس"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Try their signature Nutella or salted caramel treats.",
      "Enjoy the cozy and happy music vibe inside."
    ],
    "tips_ar": [
      "جرب حلويات النوتيلا أو الكراميل المملح المميزة عندهم.",
      "استمتع بالأجواء الهادئة والموسيقى اللطيفة جوه المكان."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: pancakes and dessert display",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: عرض البان كيك والحلويات",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "pancakes and dessert display",
    "target_object_prompt_ar": "عرض البان كيك والحلويات",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A vibrant and joyful dessert spot known for its incredible puffy pops, delicious pancakes, and friendly atmosphere that guarantees a sweet escape.",
    "description_ar": "مكان مبهج ومميز للحلويات معروف بالبوفي بوبس اللذيذ والبان كيك الشهي وأجواء مليئة بالسعادة والطاقة الإيجابية.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "b4316da2-5142-45de-9b3c-741cfc2e4cb6",
    "title": "Cilantro",
    "location": "Port Said St. Beside Bibliotheca Alexandrina, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 320,
    "clue": "اشرب قهوتك واستمتع بأحلى إطلالة على المكتبة العظيمة والبحر الساحر.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.7,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Cilantro",
    "title_ar": "سيلانترو",
    "clue_en": "Sipping coffee with a breathtaking view of the grand library and the sparkling sea.",
    "clue_ar": "اشرب قهوتك واستمتع بأحلى إطلالة على المكتبة العظيمة والبحر الساحر.",
    "riddle_answer": "Cilantro",
    "riddle_answer_ar": "سيلانترو",
    "riddle_accepted_answers": [
      "cilantro",
      "سيلانترو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Head to the second floor terrace for the best scenery.",
      "It's the perfect spot to relax after visiting the library."
    ],
    "tips_ar": [
      "اطلع على التراس في الدور التاني عشان تاخد أحلى رؤية.",
      "هو المكان المثالي للراحة بعد زيارة المكتبة."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: outdoor terrace sea view",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: التراس الخارجي المطل على البحر",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "outdoor terrace sea view",
    "target_object_prompt_ar": "التراس الخارجي المطل على البحر",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A popular cafe spot right beside Bibliotheca Alexandrina offering a lively atmosphere, great coffee, and a stunning view of the harbor and sea.",
    "description_ar": "مقهى شهير بجوار مكتبة الإسكندرية بيقدم أجواء حيوية وقهوة ممتازة مع إطلالة ساحرة ومباشرة على الميناء والبحر.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "3a78da39-3d16-46d2-ae4d-0cec2df57040",
    "title": "La Poire Cafe",
    "location": "Alexandria - Cairo desert road, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 280,
    "clue": "الوجهة الكلاسيكية للحلويات الفرنسية الغنية والمعجنات الشهية لقعدة قهوة رايقة.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.2,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "La Poire Cafe",
    "title_ar": "لابوار كافيه",
    "clue_en": "A classic destination for rich French-style sweets, delightful pastries, and a cozy coffee break.",
    "clue_ar": "الوجهة الكلاسيكية للحلويات الفرنسية الغنية والمعجنات الشهية لقعدة قهوة رايقة.",
    "riddle_answer": "La Poire Cafe",
    "riddle_answer_ar": "لابوار كافيه",
    "riddle_accepted_answers": [
      "la poire cafe",
      "لابوار كافيه"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Sample their classic mille-feuille or cheesecakes.",
      "Great spot for catching up over coffee and sweets."
    ],
    "tips_ar": [
      "جرب الميل فاي أو التشيز كيك الكلاسيكي عندهم.",
      "مكان ممتاز للقاءات السريعة وسط القهوة والحلويات."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: dessert display showcase",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فاترينة عرض الحلويات",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "dessert display showcase",
    "target_object_prompt_ar": "فاترينة عرض الحلويات",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A well-known cafe offering a wide variety of French-inspired desserts, cakes, and hot beverages in a relaxed setting.",
    "description_ar": "كافيه معروف بيقدم تشكيلة واسعة من الحلويات والتورتات والمشروبات الساخنة المستوحاة من المطبخ الفرنسي في أجواء مريحة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "f990d2c9-518d-4c18-a64b-9703afb04f59",
    "title": "The H",
    "location": "25 Mina St. Kafr Abdo, Alexandria Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 380,
    "clue": "مكان هادئ ودافئ في كفروعَبده بيقدم أكلات شهية وأجواء ضيافة ممتازة.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Hard",
    "title_en": "The H",
    "title_ar": "ذا إيتش",
    "clue_en": "A warm and inviting neighborhood eatery tucked in Kafr Abdo serving hearty meals and fresh vibes.",
    "clue_ar": "مكان هادئ ودافئ في كفروعَبده بيقدم أكلات شهية وأجواء ضيافة ممتازة.",
    "riddle_answer": "The H",
    "riddle_answer_ar": "ذا إيتش",
    "riddle_accepted_answers": [
      "the h",
      "ذا إيتش"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located on Mina Street in Kafr Abdo.",
      "Known for its welcoming staff and clean, modern setup."
    ],
    "tips_ar": [
      "موجود في شارع مينا بكفروعَبده.",
      "مشهور بطاقم العمل الودود والديكور الرايق."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: restaurant interior and cozy seating",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: ديكور المطعم والقعدات المريحة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "restaurant interior and cozy seating",
    "target_object_prompt_ar": "ديكور المطعم والقعدات المريحة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A charming hidden gem in Kafr Abdo known for its friendly staff, hearty fresh meals, and wonderfully warm atmosphere.",
    "description_ar": "ملاذ خفي وساحر في كفروعَبده معروف بفريق عمله الودود وأكلاته الطازجة وخدمته الممتازة وأجوائه الدافئة.",
    "category": "hidden_gem",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "6b8a5f9f-af50-4956-9495-1263307e2183",
    "title": "Carlos Cafe",
    "location": "6 Km Beside Mirage Mini Mall, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "عطشان وعايز ليمون بنعناع، وقاعد جنب الميراج مول؟ دور كويس وهات مكانك هنا!",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.9,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Carlos Cafe",
    "title_ar": "كافيه كارلوس",
    "clue_en": "Looking for a refreshing lemonade and mint while enjoying the lively vibe near the mall? Find your seat here!",
    "clue_ar": "عطشان وعايز ليمون بنعناع، وقاعد جنب الميراج مول؟ دور كويس وهات مكانك هنا!",
    "riddle_answer": "Carlos Cafe",
    "riddle_answer_ar": "كافيه كارلوس",
    "riddle_accepted_answers": [
      "carlos cafe",
      "كافيه كارلوس"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Try the famous lemon and mint drink.",
      "Located near Mirage Mini Mall."
    ],
    "tips_ar": [
      "جرب مشروب الليمون بالنعناع المشهور بيه.",
      "موجود جنب ميراج ميني مول."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: lemon and mint drink on a table",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: مشروب الليمون بالنعناع على الترابيزة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "lemon and mint drink on a table",
    "target_object_prompt_ar": "مشروب الليمون بالنعناع على الترابيزة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A popular spot known for its vibrant atmosphere, refreshing drinks, and family-friendly vibe near Mirage Mini Mall.",
    "description_ar": "مكان حيوي ومشهور بقعدته الحلوة ومشروباته المنعشة وأجوائه المناسبة للعائلات والجمعات قرب ميراج ميني مول.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "2937c684-4d18-43fa-9348-83dd1802c398",
    "title": "Fernando's Restaurant & Cafe",
    "location": "Al Horreya Street, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "ماشي في شارع الحرية وبتدور على أكل إيطالي مظبوط قبل المسرح؟ ادخل المكان ده.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.6,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Fernando's Restaurant & Cafe",
    "title_ar": "مطعم وكافيه فرناندو",
    "clue_en": "Strolling down Al Horreya Street and craving some Italian flavor before the theatre? Step inside this bustling venue.",
    "clue_ar": "ماشي في شارع الحرية وبتدور على أكل إيطالي مظبوط قبل المسرح؟ ادخل المكان ده.",
    "riddle_answer": "Fernando's Restaurant & Cafe",
    "riddle_answer_ar": "مطعم وكافيه فرناندو",
    "riddle_accepted_answers": [
      "fernando's restaurant & cafe",
      "مطعم وكافيه فرناندو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right on Al Horreya Street.",
      "Great choice for an Italian meal before a show."
    ],
    "tips_ar": [
      "موجود في شارع الحرية بالظبط.",
      "اختيار ممتاز لو رايح المسرح وعايز تأكل أكلة إيطالي."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Italian pasta or soup bowl on a restaurant table",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: بقالة مكرونة إيطالي أو طبق شوربة على ترابيزة المطعم",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Italian pasta or soup bowl on a restaurant table",
    "target_object_prompt_ar": "بقالة مكرونة إيطالي أو طبق شوربة على ترابيزة المطعم",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A vibrant cafe and restaurant on Al Horreya Street offering a wide variety of European and Italian dishes.",
    "description_ar": "مطعم وكافيه حيوي في شارع الحرية بيقدم تشكيلة واسعة من الأكلات الأوروبية والإيطالية.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "7bd04a0b-6e25-4a6d-83ed-50d7675c3de9",
    "title": "Arous El Selsela",
    "location": "Corniche, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 400,
    "clue": "اقعد على الصخور تحت سقف النخل قدام المكتبة العريقة، وسمع صوت الموج وهو بيخبط.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.7,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Arous El Selsela",
    "title_ar": "عروس السلسلة",
    "clue_en": "Sit right on the rocks under palm leaves, facing the great library, where the sea breeze whispers ancient secrets.",
    "clue_ar": "اقعد على الصخور تحت سقف النخل قدام المكتبة العريقة، وسمع صوت الموج وهو بيخبط.",
    "riddle_answer": "Arous El Selsela",
    "riddle_answer_ar": "عروس السلسلة",
    "riddle_accepted_answers": [
      "arous el selsela",
      "عروس السلسلة"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right in front of the Bibliotheca Alexandrina.",
      "Famous for fresh juices and shisha by the waves."
    ],
    "tips_ar": [
      "موقعه قدام مكتبة الإسكندرية على طول.",
      "مشهور بالعصائر الفريش والقعدة عالبحر مباشرة."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: palm-thatched ceiling with fairy lights overlooking the sea",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: سقف من سعف النخل مزين بإضاءة ليد وبيطل على البحر مباشرة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "palm-thatched ceiling with fairy lights overlooking the sea",
    "target_object_prompt_ar": "سقف من سعف النخل مزين بإضاءة ليد وبيطل على البحر مباشرة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "An iconic authentic Arabic cafe right on the Mediterranean shore near the Bibliotheca Alexandrina, featuring palm-leaf roofs and stunning sea views.",
    "description_ar": "قعدة عربية أصيلة على بحر إسكندرية قدام مكتبة الإسكندرية، تتميز بسقف النخل والإضاءة الهادية وقعدة الموج.",
    "category": "cultural",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "830daa8e-5366-4bcc-95f7-463b4d9620e5",
    "title": "Latino",
    "location": "El Guish Rd Beside Glim Traffic Point, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "عاوز تبدأ يومك بفطار على الميه وتختمها بالزلابيا بالشوكولاتة اللي ماحصلتش؟",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.8,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Latino",
    "title_ar": "لاتينو",
    "clue_en": "Want to start your morning with a stunning water view and finish it with legendary chocolate zalabia?",
    "clue_ar": "عاوز تبدأ يومك بفطار على الميه وتختمها بالزلابيا بالشوكولاتة اللي ماحصلتش؟",
    "riddle_answer": "Latino",
    "riddle_answer_ar": "لاتينو",
    "riddle_accepted_answers": [
      "latino",
      "لاتينو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located beside Glim Traffic Point.",
      "Don't leave without trying the chocolate zalabia."
    ],
    "tips_ar": [
      "موجود جنب نقطة مرور جليم.",
      "ميفوتكش تجرب زلابيا الشوكولاتة بتاعتهم."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: chocolate zalabia dessert plate",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: طبق زلابيا بالشوكولاتة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "chocolate zalabia dessert plate",
    "target_object_prompt_ar": "طبق زلابيا بالشوكولاتة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A premier seaside spot in Gleem offering great breakfasts, refreshing coffee, and their legendary chocolate zalabia.",
    "description_ar": "مكان مميز جداً على كورنيش جليم بيقدم فطار شرقي جامد وأحلى زلابيا بالشوكولاتة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "231d6869-262c-456e-9e7e-6e3a71f97858",
    "title": "View Cafe",
    "location": "Corneish Road Roshdy, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "قاعد في تراس الفندق في رشدي، ومستني غروب الشمس الساحر على البحر المتوسط.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.5,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "View Cafe",
    "title_ar": "فيو كافيه",
    "clue_en": "Perched inside the hotel terrace in Roshdy, this is where you watch the magnificent sunset over the Mediterranean.",
    "clue_ar": "قاعد في تراس الفندق في رشدي، ومستني غروب الشمس الساحر على البحر المتوسط.",
    "riddle_answer": "View Cafe",
    "riddle_answer_ar": "فيو كافيه",
    "riddle_accepted_answers": [
      "view cafe",
      "فيو كافيه"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located inside the Mediterranean Azur Hotel in Roshdy.",
      "Try their cold karkadeh tea or Turkish coffee."
    ],
    "tips_ar": [
      "جوه فندق ميديترينيان أزور في رشدي.",
      "جرب عندهم الكركديه السقعان أو القهوة التركي."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: outdoor terrace table with a sea horizon sunset view",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: ترابيزة في التراس الخارجي مع إطلالة غروب الشمس عالبحر",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "outdoor terrace table with a sea horizon sunset view",
    "target_object_prompt_ar": "ترابيزة في التراس الخارجي مع إطلالة غروب الشمس عالبحر",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "An open-air terrace cafe inside the Mediterranean Azur Hotel in Roshdy, perfect for enjoying a cold karkadeh tea and shisha with a panoramic sea view.",
    "description_ar": "كافيه في تراس مفتوح جوة فندق ميديترينيان أزور برشدي، مثالي للاستمتاع بالشيشة والكركديه السقعان وإطلالة بانورامية عالبحر.",
    "category": "entertainment",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "fd822126-0bd2-4e31-ab1f-aa2fa7a04a3d",
    "title": "Saltanat Stanley Cafe",
    "location": "259 Elgish Street, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "فين كوبري ستانلي ما بينور بليل والهوا بيرمي ع البحر، تعالي اشرب قهوتك عالي.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Saltanat Stanley Cafe",
    "title_ar": "كافيه سلطنة ستانلي",
    "clue_en": "Where the majestic bridge meets the sea breeze, find royal coffee by the eastern shore.",
    "clue_ar": "فين كوبري ستانلي ما بينور بليل والهوا بيرمي ع البحر، تعالي اشرب قهوتك عالي.",
    "riddle_answer": "Saltanat Stanley Cafe",
    "riddle_answer_ar": "سلطنة ستانلي",
    "riddle_accepted_answers": [
      "saltanat stanley cafe",
      "كافيه سلطنة ستانلي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Look for the cafe near Stanley Bridge.",
      "Enjoy the view of the sea while you search."
    ],
    "tips_ar": [
      "دور على الكافيه القريب من كوبري ستانلي.",
      "استمتع بمنظر البحر وأنت بتدور."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: seaside cafe view",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: إطلالة الكافيه على البحر",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "seaside cafe view",
    "target_object_prompt_ar": "إطلالة الكافيه على البحر",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A charming cafe located near the famous Stanley Bridge offering stunning Mediterranean views and a relaxing atmosphere.",
    "description_ar": "كافيه ساحر يقع بالقرب من كوبري ستانلي الشهير، يوفر إطلالات خلابة على البحر الأبيض المتوسط وأجواء مريحة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "daabba9b-af6c-40d9-979a-1b388c9cce0e",
    "title": "Fresco Gelateria",
    "location": "48 Rue Fouad, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 320,
    "clue": "في شارع فؤاد العريق، دور على الآيس كريم الإيطالي اللي يروق المزاج.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.6,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Fresco Gelateria",
    "title_ar": "فريسكو جيلاتي",
    "clue_en": "On Fouad Street where history flows, scoop up a taste of Italy where the sweet tooth goes.",
    "clue_ar": "في شارع فؤاد العريق، دور على الآيس كريم الإيطالي اللي يروق المزاج.",
    "riddle_answer": "Fresco Gelateria",
    "riddle_answer_ar": "فريسكو جيلاتي",
    "riddle_accepted_answers": [
      "fresco gelateria",
      "فريسكو جيلاتي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right on famous Fouad Street.",
      "Check out the wall with Italian phrases."
    ],
    "tips_ar": [
      "موجود في شارع فؤاد المشهور.",
      "بص على الحائط اللي عليه جمل إيطالية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: gelato display counter",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فترينة عرض الجيلاتي",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "gelato display counter",
    "target_object_prompt_ar": "فترينة عرض الجيلاتي",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A premier gelateria on historic Fouad Street serving exquisite Italian gelato, frozen yogurt, and tasty crepes.",
    "description_ar": "محل جيلاتي متميز في شارع فؤاد التاريخي، يقدم الآيس كريم الإيطالي الفاخر، والزبادي المجمد، والكراب اللذيذ.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "d3114779-cf5f-4a3f-96fa-9cf5941c403c",
    "title": "Cilantro",
    "location": "San Stefano Mall, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 280,
    "clue": "قهوة سريعة ومظبوطة جوه مول كبير، مكان تجمع الصحاب والطلبة.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Cilantro",
    "title_ar": "سيلانترو",
    "clue_en": "A bustling modern brew inside a famous mall, perfect for a quick coffee call.",
    "clue_ar": "قهوة سريعة ومظبوطة جوه مول كبير، مكان تجمع الصحاب والطلبة.",
    "riddle_answer": "Cilantro",
    "riddle_answer_ar": "سيلانترو",
    "riddle_accepted_answers": [
      "cilantro",
      "سيلانترو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located inside San Stefano Mall.",
      "Great spot for a quick iced coffee or ginger cookie."
    ],
    "tips_ar": [
      "موجود جوه مول سان ستيفانو.",
      "مكان ممتاز لقهوة مثلجة سريعة أو بسكويت."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: coffee counter and pastry display",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: ركن القهوة وعرض المعجنات",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "coffee counter and pastry display",
    "target_object_prompt_ar": "ركن القهوة وعرض المعجنات",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A popular café chain known for its reliable coffee, cozy seating, and sweet treats near San Stefano.",
    "description_ar": "سلسلة مقاهي شهيرة معروفة بقهوتها الموثوقة، وجلساتها المريحة، والحلويات اللذيذة بالقرب من سان ستيفانو.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "5563d680-f5a8-48de-90b7-405ce5150601",
    "title": "Kenoz Restaurant & Oriental Cafe at San Stefano Mall",
    "location": "El-Gaish Road San Stefano Mall 1St Floor, Sea Side, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "قعدة عربية أصيلة وشيشة رايقة وإطلالة بحرية جوه المول.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Kenoz Restaurant & Oriental Cafe at San Stefano Mall",
    "title_ar": "مطعم وكافيه كنوز",
    "clue_en": "Hidden away with Middle Eastern flair and sea views to spare.",
    "clue_ar": "قعدة عربية أصيلة وشيشة رايقة وإطلالة بحرية جوه المول.",
    "riddle_answer": "Kenoz Restaurant & Oriental Cafe at San Stefano Mall",
    "riddle_answer_ar": "كنوز",
    "riddle_accepted_answers": [
      "kenoz restaurant & oriental cafe at san stefano mall",
      "مطعم وكافيه كنوز"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Look on the first floor of San Stefano Mall.",
      "Known for its stunning oriental rooms and shisha."
    ],
    "tips_ar": [
      "دوره في الدور الأول من مول سان ستيفانو.",
      "مشهور بغرفه الشرقية المميزة وشيشته."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Middle Eastern interior decor",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: الديكور الشرقي الداخلي",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Middle Eastern interior decor",
    "target_object_prompt_ar": "الديكور الشرقي الداخلي",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "An oriental cafe and restaurant offering stunning sea views, Middle Eastern decor, and delicious shisha.",
    "description_ar": "موقع شرقي يقدم إطلالات بحرية مذهلة، وديكورات شرق أوسطية، وشيشة ممتازة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "27f2d159-3b75-4158-a6ba-c4c5af5eddde",
    "title": "Roastery coffee",
    "location": "Fouad street Kafr-Abdo, Alexandria 12556 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "في قلب شارع فؤاد، مكان حيوي للقهوة والحلويات والمشاوي.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.1,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Roastery coffee",
    "title_ar": "روستري كوفي",
    "clue_en": "On Fouad Street's bustling beat, find a vibrant spot for a coffee treat.",
    "clue_ar": "في قلب شارع فؤاد، مكان حيوي للقهوة والحلويات والمشاوي.",
    "riddle_answer": "Roastery coffee",
    "riddle_answer_ar": "روستري",
    "riddle_accepted_answers": [
      "roastery coffee",
      "روستري كوفي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located on Fouad Street.",
      "Famous for its extensive menu and desserts."
    ],
    "tips_ar": [
      "يقع في شارع فؤاد.",
      "مشهور بقائمة طعامه المتنوعة والحلويات."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: coffee roasting station",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: ركن تحميص القهوة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "coffee roasting station",
    "target_object_prompt_ar": "ركن تحميص القهوة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A contemporary cafe and restaurant on Fouad Street offering a wide variety of meals, coffee, and wonderful desserts.",
    "description_ar": "مقهى ومطعم معاصر في شارع فؤاد يقدم مجموعة واسعة من الوجبات والقهوة والحلويات الرائعة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "51f60113-8708-4594-83a1-568e3eda8133",
    "title": "Tiffany Cafe",
    "location": "Stanly 2 Zaki Badawi St, Alexandria Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 250,
    "clue": "على هواء ستانلي والقهوة الطلياني، اوعى تنسى تطلب الحلو عشان تمشي سليماني!",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 1.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Tiffany Cafe",
    "title_ar": "تيفاني كافيه",
    "clue_en": "Where Stanley's breeze meets Italian coffee, don't forget to order your dessert just to be safe!",
    "clue_ar": "على هواء ستانلي والقهوة الطلياني، اوعى تنسى تطلب الحلو عشان تمشي سليماني!",
    "riddle_answer": "Tiffany Cafe",
    "riddle_answer_ar": "تيفاني كافيه",
    "riddle_accepted_answers": [
      "tiffany cafe",
      "تيفاني كافيه"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located in Stanly near Zaki Badawi St.",
      "Known for coffee and Italian snacks."
    ],
    "tips_ar": [
      "يقع في ستانلي بالقرب من شارع زكي بدوي.",
      "معروف بالقهوة والوجبات الخفيفة الإيطالية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Italian coffee cup and dessert menu",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فنجان القهوة الإيطالي وقائمة الحلويات",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Italian coffee cup and dessert menu",
    "target_object_prompt_ar": "فنجان القهوة الإيطالي وقائمة الحلويات",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A cozy café located near Stanley St Zaki Badawi Street in Alexandria, offering a mix of Italian and Mediterranean bites.",
    "description_ar": "كافيه هادئ يقع بالقرب من شارع زكي بدوي بمنطقة ستانلي في الإسكندرية، ويقدم تشكيلة من المأكولات الإيطالية والمتوسطية.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "fb88b21c-d214-4092-85d4-fcc5bc74932f",
    "title": "costa",
    "location": "",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "بمساحة بتطل على البحر المتوسط وكوبري ستانلي، اطلب قهوتك المفضلة واستمتع بالغروب.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.8,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "costa",
    "title_ar": "كوستا كافيه",
    "clue_en": "Overlooking the gorgeous Mediterranean Sea and Stanley Bridge, grab your favorite brew here.",
    "clue_ar": "بمساحة بتطل على البحر المتوسط وكوبري ستانلي، اطلب قهوتك المفضلة واستمتع بالغروب.",
    "riddle_answer": "costa",
    "riddle_answer_ar": "كوستا كافيه",
    "riddle_accepted_answers": [
      "costa",
      "كوستا كافيه"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Great sunset views of Stanley Bridge.",
      "Popular outlet located near San Stefano."
    ],
    "tips_ar": [
      "إطلالات رائعة على غروب الشمس وكوبري ستانلي.",
      "فرع شهير يقع بالقرب من سان ستفانو."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Coffee cup with a sea view background",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فنجان القهوة مع خلفية إطلالة البحر",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Coffee cup with a sea view background",
    "target_object_prompt_ar": "فنجان القهوة مع خلفية إطلالة البحر",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A popular café brand outlet, notably nice in San Stefano mall, offering great coffee and views of the Mediterranean.",
    "description_ar": "فرع شهير لكوستا كافيه، يتميز بموقعه الجميل في مول سان ستفانو وإطلالته الرائعة على البحر الأبيض المتوسط.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "78308fea-0fd2-47b4-b2b3-b10f5e47cf2e",
    "title": "Brew & Chew",
    "location": "28 Kafr Abdou street, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "جنة عشاق الشوكولاتة في كفر عبده، حيث المولتن كيك والفوندو هما سيد المكان!",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.2,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Brew & Chew",
    "title_ar": "برو آند تشيو",
    "clue_en": "A chocolate lover's absolute paradise in Kafr Abdou, where molten cakes and fondue rule!",
    "clue_ar": "جنة عشاق الشوكولاتة في كفر عبده، حيث المولتن كيك والفوندو هما سيد المكان!",
    "riddle_answer": "Brew & Chew",
    "riddle_answer_ar": "برو آند تشيو",
    "riddle_accepted_answers": [
      "brew & chew",
      "برو آند تشيو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located on Kafr Abdou street.",
      "Famous for chocolate fondue and sweet treats."
    ],
    "tips_ar": [
      "يقع في شارع كفر عبده الشهير.",
      "مشهور بفوندو الشوكولاتة والحلويات الغنية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Chocolate fondue or molten cake dessert",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فوندو الشوكولاتة أو حلوى المولتن كيك",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Chocolate fondue or molten cake dessert",
    "target_object_prompt_ar": "فوندو الشوكولاتة أو حلوى المولتن كيك",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A fantastic dessert and coffee spot in the vibrant neighborhood of Kafr Abdou, famous for its rich chocolate treats.",
    "description_ar": "وجهة رائعة للحلويات والقهوة في حي كفر عبده الراقي، وتشتهر بأطباق الشوكولاتة الغنية واللذيذة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "ca91427f-3b12-4b43-a4be-51b4e671bae8",
    "title": "Imperial Cafe & Restaurant",
    "location": "Saad Zaghloul Square, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 400,
    "clue": "ارجع بالزمن لورا وإنت شايف محطة الرمل قدامك من قلب وسط البلد التاريخي.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Hard",
    "title_en": "Imperial Cafe & Restaurant",
    "title_ar": "مقهى ومطعم إمبريال",
    "clue_en": "Step back in time with a nostalgic view of Al Raml Station in old downtown Alexandria.",
    "clue_ar": "ارجع بالزمن لورا وإنت شايف محطة الرمل قدامك من قلب وسط البلد التاريخي.",
    "riddle_answer": "Imperial Cafe & Restaurant",
    "riddle_answer_ar": "مقهى إمبريال",
    "riddle_accepted_answers": [
      "imperial cafe & restaurant",
      "مقهى ومطعم إمبريال"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right at Saad Zaghloul Square / Al Raml Station.",
      "Features a classic, vintage Alexandria atmosphere."
    ],
    "tips_ar": [
      "يقع مباشرة في ميدان سعد زغلول / محطة الرمل.",
      "يتميز بأجواء الإسكندرية الكلاسيكية والقديمة."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Nostalgic interior decor showing old Alexandria history",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: الديكور الداخلي التراثي الذي يعكس تاريخ الإسكندرية",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Nostalgic interior decor showing old Alexandria history",
    "target_object_prompt_ar": "الديكور الداخلي التراثي الذي يعكس تاريخ الإسكندرية",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A historical and dated cozy cafe right at Saad Zaghloul Square, capturing the old soul and vintage history of Alexandria.",
    "description_ar": "مقهى تراثي دافئ يقع في ميدان سعد زغلول، ويعكس بامتياز الروح التاريخية والأصالة لمدينة الإسكندرية القديمة.",
    "category": "history",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "46d66f4d-9071-4c17-accd-51ee75c47745",
    "title": "Mo Brew",
    "location": "Bab Sharqi WA Wabour Al Meyah Bab Shar', Alexandria 5422023 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "مكان رايق ومخبي في باب شرق، بمشروبات ممتازة وقعدة هادية تروق الدم.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Mo Brew",
    "title_ar": "مو برو",
    "clue_en": "A cozy hidden gem in Bab Sharqi with top-notch drinks and a super chill ambiance.",
    "clue_ar": "مكان رايق ومخبي في باب شرق، بمشروبات ممتازة وقعدة هادية تروق الدم.",
    "riddle_answer": "Mo Brew",
    "riddle_answer_ar": "مو برو",
    "riddle_accepted_answers": [
      "mo brew",
      "مو برو"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located in Bab Sharqi, Alexandria.",
      "Known for its cozy atmosphere and quality drinks."
    ],
    "tips_ar": [
      "يقع في منطقة باب شرق بالإسكندرية.",
      "معروف بأجوائه المريحة ومشروباته عالية الجودة."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Cozy coffee bar counter with specialty drinks",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: بار القهوة الدافئ والمشروبات المختصة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Cozy coffee bar counter with specialty drinks",
    "target_object_prompt_ar": "بار القهوة الدافئ والمشروبات المختصة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A cozy, highly rated neighborhood café in Bab Sharqi offering incredible specialty drinks and a relaxing atmosphere.",
    "description_ar": "مقهى هادئ ومميز في باب شرق، يقدم مشروبات استثنائية بجودة عالية وأجواء مريحة للغاية.",
    "category": "hidden_gem",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "2977ab84-33f0-4331-b29a-f1da9e8062c0",
    "title": "Red Rose Cafe",
    "location": "Green Plaza, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 250,
    "clue": "دور على مكان هادي في جرين بلازا وقواعد السيجار والكراسي ممكن تختبر صبرك؟ الاقي طريقك للوردة دي.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 2.5,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Red Rose Cafe",
    "title_ar": "كافيه ريد روز",
    "clue_en": "Looking for a quiet spot in Green Plaza where rules on cigars and seating might test your patience? Find your way to this rose.",
    "clue_ar": "دور على مكان هادي في جرين بلازا وقواعد السيجار والكراسي ممكن تختبر صبرك؟ الاقي طريقك للوردة دي.",
    "riddle_answer": "Red Rose Cafe",
    "riddle_answer_ar": "كافيه ريد روز",
    "riddle_accepted_answers": [
      "red rose cafe",
      "كافيه ريد روز"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located in Green Plaza, Alexandria.",
      "Known for a quiet lounge atmosphere."
    ],
    "tips_ar": [
      "يقع في جرين بلازا، الإسكندرية.",
      "معروف بأجواء صالة هادئة."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: lounge chairs and couch",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: كراسي صالون مريحة وأريكة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "lounge chairs and couch",
    "target_object_prompt_ar": "كراسي صالون مريحة وأريكة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A quiet cafe located in Green Plaza, Alexandria, offering a place to unwind despite some strict indoor seating and smoking policies.",
    "description_ar": "مقهى هادئ يقع في جرين بلازا بالإسكندرية، يوفر مكانا للاسترخاء رغم بعض السياسات الصارمة بشأن الجلوس والتدخين.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "1339b3ef-9732-4b22-b0a4-472700c683a6",
    "title": "Trianon Sidi Bishr",
    "location": "El Geish Rd, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "اشرب شايك واتفرج على جداريات الآرت ديكو مع إطلالة بحرية ساحرة بتهمس بتاريخ إسكندراني ودنماركي.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.9,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Trianon Sidi Bishr",
    "title_ar": "تريانون سيدي بشر",
    "clue_en": "Sip your tea and admire the Art Deco murals with a magical sea view that whispers Danish and Alexandrian history.",
    "clue_ar": "اشرب شايك واتفرج على جداريات الآرت ديكو مع إطلالة بحرية ساحرة بتهمس بتاريخ إسكندراني ودنماركي.",
    "riddle_answer": "Trianon Sidi Bishr",
    "riddle_answer_ar": "تريانون",
    "riddle_accepted_answers": [
      "trianon sidi bishr",
      "تريانون سيدي بشر"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Enjoy the outdoor seating facing the sea.",
      "Check out the historic wall murals and pastries."
    ],
    "tips_ar": [
      "استمتع بالجلوس الخارجي في مواجهة البحر.",
      "تفرج على الجداريات التاريخية والحلويات."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Art Deco wall murals",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: جداريات آرت ديكو الفنية",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Art Deco wall murals",
    "target_object_prompt_ar": "جداريات آرت ديكو الفنية",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "An iconic Art Deco venue on El Geish Road offering a magnificent sea view, fine desserts, and a timeless Alexandrian atmosphere.",
    "description_ar": "مكان عريق بطراز آرت ديكو على طريق الجيش يوفر إطلالة بحرية رائعة، حلويات فاخرة، وأجواء إسكندرية خالدة.",
    "category": "cultural",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "bdd45be3-2a9f-4e9c-ab61-f825fd059bc4",
    "title": "Alexandria Tivoli Dome",
    "location": "Algeish Street, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "حيث تقابل المطاعم المتنوعة والنافورة قرب كوبري ستانلي، لتقدم تجمع حيوي للسهرات.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.1,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Alexandria Tivoli Dome",
    "title_ar": "تيفولي دوم الإسكندرية",
    "clue_en": "Where multiple cuisines and fountains meet near Stanley Bridge, offering a bustling hub for evening gatherings.",
    "clue_ar": "حيث تقابل المطاعم المتنوعة والنافورة قرب كوبري ستانلي، لتقدم تجمع حيوي للسهرات.",
    "riddle_answer": "Alexandria Tivoli Dome",
    "riddle_answer_ar": "تيفولي دوم",
    "riddle_accepted_answers": [
      "alexandria tivoli dome",
      "تيفولي دوم الإسكندرية"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right on Algeish Street near Stanley.",
      "Great spot for evening walks and dining options."
    ],
    "tips_ar": [
      "يقع مباشرة على شارع الجيش قرب ستانلي.",
      "مكان رائع للتمشية المسائية وخيارات الطعام."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: side fountains and open area",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: النافورة الجانبية والمنطقة المفتوحة",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "side fountains and open area",
    "target_object_prompt_ar": "النافورة الجانبية والمنطقة المفتوحة",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A vibrant entertainment and dining complex on Algeish Street, famous for its open-air spaces and stunning views of Stanley Bridge.",
    "description_ar": "مجمع ترفيهي وتناولي حيوي على شارع الجيش، مشهور بمساحاته المفتوحة وإطلالاته الخلابة على كوبري ستانلي.",
    "category": "entertainment",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "c42c3c90-5c09-4dea-b2b8-3d2d9b4746f2",
    "title": "Brazilian Coffee",
    "location": "44 Saad Zaghloul St., Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 400,
    "clue": "ارجع بالزمن لشارع سعد زغلول عشان تاخد فنجان قهوة تركي تاريخي له عراقة إسكندرانية.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.2,
    "distance": null,
    "is_active": true,
    "difficulty": "Hard",
    "title_en": "Brazilian Coffee",
    "title_ar": "البن البرازيلي",
    "clue_en": "Step back in time on Saad Zaghloul Street for a legendary cup of Turkish coffee steeped in local history.",
    "clue_ar": "ارجع بالزمن لشارع سعد زغلول عشان تاخد فنجان قهوة تركي تاريخي له عراقة إسكندرانية.",
    "riddle_answer": "Brazilian Coffee",
    "riddle_answer_ar": "البن البرازيلي",
    "riddle_accepted_answers": [
      "brazilian coffee",
      "البن البرازيلي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located at 44 Saad Zaghloul St.",
      "Famous for its standing bar and traditional Turkish coffee."
    ],
    "tips_ar": [
      "يقع في 44 شارع سعد زغلول.",
      "مشهور بالوقوف على البار والقهوة التركي التقليدية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: historic coffee grinding machines and vintage decor",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: ماكينات طحن القهوة التاريخية والديكور القديم",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "historic coffee grinding machines and vintage decor",
    "target_object_prompt_ar": "ماكينات طحن القهوة التاريخية والديكور القديم",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A historic coffee institution on Saad Zaghloul Street serving authentic blends and vintage charm since 1929.",
    "description_ar": "مؤسسة قهوة عريقة في شارع سعد زغلول تقدم خلطات أصيلة وسحر تاريخي منذ عام 1929.",
    "category": "history",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "8963fbad-e259-4cf9-8cd4-4a89d1cc542c",
    "title": "Brazilian Coffee",
    "location": "20 Salah Salem St. in Front Of Alex Bank, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "الاقي فرع صلاح سالم الكلاسيكي ده قدام بنك الإسكندرية، حيث ريحة القهوة التركي الأصيلة من سنين بتستقبلك.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.4,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Brazilian Coffee",
    "title_ar": "البن البرازيلي",
    "clue_en": "Find this classic Salah Salem branch in front of Alex Bank, where the aroma of decades-old Turkish coffee welcomes you.",
    "clue_ar": "الاقي فرع صلاح سالم الكلاسيكي ده قدام بنك الإسكندرية، حيث ريحة القهوة التركي الأصيلة من سنين بتستقبلك.",
    "riddle_answer": "Brazilian Coffee",
    "riddle_answer_ar": "البن البرازيلي",
    "riddle_accepted_answers": [
      "brazilian coffee",
      "البن البرازيلي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located at 20 Salah Salem St. in front of Alex Bank.",
      "A must-visit for traditional coffee lovers."
    ],
    "tips_ar": [
      "يقع في 20 شارع صلاح سالم في مواجهة بنك الإسكندرية.",
      "مكان لا بد من زيارته لعشاق القهوة التقليدية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: vintage wooden counter and coffee jars",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: البار الخشبي القديم وبرطمانات البن",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "vintage wooden counter and coffee jars",
    "target_object_prompt_ar": "البار الخشبي القديم وبرطمانات البن",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "The iconic Salah Salem branch of the legendary Brazilian Coffee stores, offering rich history and a wonderful cup of Turkish coffee.",
    "description_ar": "فرع صلاح سالم الأيقوني لمتاجر البن البرازيلي الشهيرة، يقدم تاريخا عريقا وفنجان قهوة تركي رائع.",
    "category": "history",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "20f7a857-d036-405c-b6dd-57abffefac23",
    "title": "Costa Coffee",
    "location": "",
    "lat": null,
    "lng": null,
    "reward_coins": 300,
    "clue": "مكان على كوبري ستانلی البحر قدامك، اشرب قهوتك واستمتع بالمنظر الجميل.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 3.9,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Costa Coffee",
    "title_ar": "كوستا كوفي",
    "clue_en": "Where the sea breeze meets Stanley Bridge, sip your brew with a scenic view.",
    "clue_ar": "مكان على كوبري ستانلی البحر قدامك، اشرب قهوتك واستمتع بالمنظر الجميل.",
    "riddle_answer": "Costa Coffee",
    "riddle_answer_ar": "كوستا كوفي",
    "riddle_accepted_answers": [
      "costa coffee",
      "كوستا كوفي"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Look for the second floor for the best sea view.",
      "Close to the famous Stanley Bridge."
    ],
    "tips_ar": [
      "دور على الدور التاني عشان تشوف أحسن إطلالة بحر.",
      "قريب من كوبري ستانلي المشهور."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: Stanley Bridge sea view",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: إطلالة بحر كوبري ستانلي",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "Stanley Bridge sea view",
    "target_object_prompt_ar": "إطلالة بحر كوبري ستانلي",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A popular spot by the iconic Stanley Bridge offering breathtaking sea views and top-notch coffee.",
    "description_ar": "مكان شهير عند كوبري ستانلي الأيقوني يوفر إطلالات بحرية خلابة وقهوة عالية الجودة.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "4a93a6a8-e3b4-449f-85aa-d994ae1298b5",
    "title": "Starbucks",
    "location": "San Stephano Mall San Stefano Grand Plaza Mall, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 250,
    "clue": "على كورنيش سان ستيفانو قدام البحر الأبيض، اطلب اللاتيه المفضل ليك.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.2,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Starbucks",
    "title_ar": "ستاربكس",
    "clue_en": "Right by the Mediterranean coast in San Stefano, grab your favorite latte on the go.",
    "clue_ar": "على كورنيش سان ستيفانو قدام البحر الأبيض، اطلب اللاتيه المفضل ليك.",
    "riddle_answer": "Starbucks",
    "riddle_answer_ar": "ستاربكس",
    "riddle_accepted_answers": [
      "starbucks",
      "ستاربكس"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located near San Stefano Grand Plaza.",
      "Great spot to enjoy a cafe latte."
    ],
    "tips_ar": [
      "موجود قرب سان ستيفانو جراند بلازا.",
      "مكان ممتاز للاستمتاع بقهوة اللاتيه."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: outdoor seating umbrella",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: شمسية الجلسات الخارجية",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "outdoor seating umbrella",
    "target_object_prompt_ar": "شمسية الجلسات الخارجية",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A bustling international coffeehouse chain located right across from the Mediterranean Sea.",
    "description_ar": "فرع شهير لسلسلة المقاهي العالمية يقع مباشرة مقابل البحر الأبيض المتوسط.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "22e7ac0f-5bfb-4631-967a-f4d354bb0c1c",
    "title": "Cascada Cafe & Restaurant",
    "location": "16 Mohammed Hussein, Alexandria 21599 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 350,
    "clue": "مكان دافي ومستخبى في شارع محمد حسين لوجبة سريعة ولذيذة.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Medium",
    "title_en": "Cascada Cafe & Restaurant",
    "title_ar": "كاسكيد كافيه أند رستورانت",
    "clue_en": "A cozy neighborhood spot tucked away on Mohammed Hussein street for a quick bite.",
    "clue_ar": "مكان دافي ومستخبى في شارع محمد حسين لوجبة سريعة ولذيذة.",
    "riddle_answer": "Cascada Cafe & Restaurant",
    "riddle_answer_ar": "كاسكيد كافيه",
    "riddle_accepted_answers": [
      "cascada cafe & restaurant",
      "كاسكيد كافيه أند رستورانت"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located on Mohammed Hussein street.",
      "Known for pizza and fast food options."
    ],
    "tips_ar": [
      "يقع في شارع محمد حسين.",
      "معروف بخيارات البيتزا والأكل السريع."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: menu board",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: لوحة قائمة الطعام",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "menu board",
    "target_object_prompt_ar": "لوحة قائمة الطعام",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A charming and cozy local cafe and restaurant offering a variety of quick bites and pizzas.",
    "description_ar": "كافيه ومطعم محلي ساحر ودافئ يقدم مجموعة متنوعة من الأكلات السريعة والبيتزا.",
    "category": "hidden_gem",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "25a98b1f-b2ce-44fc-8678-8b19cbb07740",
    "title": "Delices",
    "location": "46 Saad Zhaghloul Street Raml Station, Alexandria 5372044 Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 400,
    "clue": "ادخل عالم الأناقة التاريخية قرب محطة الرمل حيث التراث اليوناني والحلويات اللذيذة.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 4.1,
    "distance": null,
    "is_active": true,
    "difficulty": "Hard",
    "title_en": "Delices",
    "title_ar": "ديليس",
    "clue_en": "Step into historic elegance near Raml Station where Greek heritage and sweets collide.",
    "clue_ar": "ادخل عالم الأناقة التاريخية قرب محطة الرمل حيث التراث اليوناني والحلويات اللذيذة.",
    "riddle_answer": "Delices",
    "riddle_answer_ar": "ديليس",
    "riddle_accepted_answers": [
      "delices",
      "ديليس"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located right by Saad Zaghloul Street near Raml Station.",
      "Famous for Turkish coffee and historic ambiance."
    ],
    "tips_ar": [
      "يقع بجوار شارع سعد زغلول قرب محطة الرمل.",
      "مشهور بالقهوة التركية والأجواء التاريخية."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: historic pastry display counter",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: فترينة عرض الحلويات التاريخية",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "historic pastry display counter",
    "target_object_prompt_ar": "فترينة عرض الحلويات التاريخية",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A legendary historic cafe and confectionery near Raml Station famous for its Greek charm and delicious desserts.",
    "description_ar": "كافيه ومحل حلويات تاريخي أسطوري قرب محطة الرمل يشتهر بطابعه اليوناني وحلوياته الشهية.",
    "category": "history",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  },
  {
    "id": "a694abec-6c07-4379-b67b-527ed8cb89df",
    "title": "Waffle's Cleopatra Branch",
    "location": "163 El El-gaish Rd, Sidi Gabir, Sidi Gaber, Alexandria Governorate 21618, Alexandria Egypt",
    "lat": null,
    "lng": null,
    "reward_coins": 250,
    "clue": "وافل ذهبي ومقرمش نازل عليه الشوكولاتة على طريق الجيش الحنطور.",
    "align_x": null,
    "align_y": null,
    "type_icon": "cafe",
    "rating": 5.0,
    "distance": null,
    "is_active": true,
    "difficulty": "Easy",
    "title_en": "Waffle's Cleopatra Branch",
    "title_ar": "وافلز فرع كليوباترا",
    "clue_en": "Crispy golden treats dripping in chocolate along the bustling El-Geish road.",
    "clue_ar": "وافل ذهبي ومقرمش نازل عليه الشوكولاتة على طريق الجيش الحنطور.",
    "riddle_answer": "Waffle's Cleopatra Branch",
    "riddle_answer_ar": "وافلز",
    "riddle_accepted_answers": [
      "waffle's cleopatra branch",
      "وافلز فرع كليوباترا"
    ],
    "created_at": null,
    "qr_code": null,
    "initial_reward": null,
    "min_reward": null,
    "decay_rate_per_hour": null,
    "is_todays_gem": false,
    "is_squad": false,
    "required_squad_size": 1,
    "estimate_time": "30 mins",
    "image_url": "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?q=80&w=1000&auto=format&fit=crop",
    "tips_en": [
      "Located on El-Geish Road in Sidi Gaber.",
      "Open late night for sweet cravings."
    ],
    "tips_ar": [
      "موجود على طريق الجيش في سيدي جابر.",
      "مفتوح لحد متأخر لو حسيت برغبة في الحلويات."
    ],
    "activated_at": null,
    "is_mega": false,
    "expires_at": null,
    "brand_id": null,
    "special_instruction": null,
    "special_instruction_ar": null,
    "max_claims_capacity": null,
    "hero_image_url": null,
    "banner_image_url": null,
    "banner_title_en": null,
    "banner_title_ar": null,
    "banner_bg_color": null,
    "sponsor_name": null,
    "sponsor_logo_url": null,
    "merchant_cta_url": null,
    "merchant_cta_text": null,
    "merchant_cta_text_ar": null,
    "mega_type": null,
    "starts_at": null,
    "requires_photo_proof": true,
    "photo_instructions": "Take a clear photo of: freshly baked waffle display",
    "photo_instructions_ar": "صوّر صورة واضحة لـ: عرض الوافل الطازج",
    "secret_menu_title": null,
    "secret_menu_duration_mins": null,
    "is_pulse_radar": false,
    "is_lens_hunter": true,
    "is_jogo_spy": false,
    "target_object_prompt": "freshly baked waffle display",
    "target_object_prompt_ar": "عرض الوافل الطازج",
    "game_mode": "lens_hunter",
    "notification_radius_meters": 200,
    "created_by": null,
    "created_by_user_id": null,
    "description_en": "A delightful waffle shop on El-Geish road serving light, fluffy, and perfectly golden Belgian waffles.",
    "description_ar": "محل وافل رائع على طريق الجيش يقدم وافل بلجيكي خفيف وهش ومحمر بشكل مثالي.",
    "category": "food",
    "city": "Alexandria",
    "max_squad_size": 5,
    "squad_split_reward": false,
    "geofence_radius_meters": 70,
    "radar_found_radius_meters": 15,
    "cooldown_hours_per_user": 168,
    "max_daily_attempts_per_user": 5,
    "badge_label_en": "Mega Quest",
    "badge_label_ar": "مهمة كبرى"
  }
];